src/src/Entity/Clients.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\CardScheme;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientsRepository")
 */
class Clients
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $credit_card_number;

    /**
     * @param ClassMetadata $metadata
     */
    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('name', new NotBlank());
        $metadata->addPropertyConstraint('last_name', new NotBlank());
        $metadata->addPropertyConstraint('email', new Email([
            'message' => 'The email "{{ value }}" is not a valid email.',
        ]));
        $metadata->addPropertyConstraint('phone', new NotBlank());
        $metadata->addPropertyConstraint('credit_card_number', new CardScheme([
            'schemes' => [
                'VISA', 'MASTERCARD'
            ],
            'message' => 'Your credit card number is invalid.',
        ]));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCreditCardNumber(): ?string
    {
        return $this->credit_card_number;
    }

    public function setCreditCardNumber(string $credit_card_number): self
    {
        $this->credit_card_number = $credit_card_number;

        return $this;
    }
}

src/src/Form/ClientsType.php
<?php

namespace App\Form;

use App\Entity\Clients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('last_name')
            ->add('email')
            ->add('phone')
            ->add('credit_card_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Clients::class,
        ]);
    }
}

src/src/Controller/ClientsController.php
<?php

namespace App\Controller;

use App\Entity\Clients;
use App\Form\ClientsType;
use App\Repository\ClientsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/clients")
 */
class ClientsController extends AbstractController
{
    /**
     * @Route("/", name="clients_index", methods={"GET"})
     */
    public function index(ClientsRepository $clientsRepository): Response
    {
        return $this->render('clients/index.html.twig', [
            'clients' => $clientsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="clients_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $client = new Clients();
        $form = $this->createForm(ClientsType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('clients_index');
        }

        return $this->render('clients/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="clients_show", methods={"GET"})
     */
    public function show(Clients $client): Response
    {
        return $this->render('clients/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="clients_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Clients $client): Response
    {
        $form = $this->createForm(ClientsType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('clients_index');
        }

        return $this->render('clients/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="clients_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Clients $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('clients_index');
    }
}

src/src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="")
     * @Template
     */
    public function index()
    {
    }
}

src/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" type="text/css"  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css"/>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="/">Fernando Gil</a>
        </nav>
        <div class="container">
            {% block body %}{% endblock %}
            {% block javascripts %}{% endblock %}
        </div>
    </body>
</html>

src/templates/clients/_delete_form.html.twig
<form method="post" action="{{ path('clients_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn btn-warning float-left">Delete</button>
</form>

src/templates/clients/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary float-left">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

src/templates/clients/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Clients{% endblock %}

{% block body %}
    <h1>Edit Clients</h1>

    {{ include('clients/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('clients_index') }}" class="float-right">back to list</a>

    {{ include('clients/_delete_form.html.twig') }}
{% endblock %}

src/templates/clients/form_div_layout.html.twig
{% block form_widget_simple %}
    {% set type = type|default('text') %}xcvxc
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
{% endblock form_widget_simple %}

src/templates/clients/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients index{% endblock %}

{% block body %}
    <h1>Clients index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Last_name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Credit_card_number</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.name }}</td>
                <td>{{ client.lastName }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.phone }}</td>
                <td>{{ client.creditCardNumber }}</td>
                <td>
                    <a href="{{ path('clients_show', {'id': client.id}) }}">show</a>
                    <a href="{{ path('clients_edit', {'id': client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('clients_new') }}">Create new</a>
{% endblock %}

src/templates/clients/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Clients{% endblock %}

{% block body %}
    <h1>Create new Clients</h1>

    {{ include('clients/_form.html.twig') }}

    <a href="{{ path('clients_index') }}" class="float-right">back to list</a>
{% endblock %}

src/templates/clients/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients{% endblock %}

{% block body %}
    <h1>Clients</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ client.name }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ client.lastName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ client.email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ client.phone }}</td>
            </tr>
            <tr>
                <th>Credit_card_number</th>
                <td>{{ client.creditCardNumber }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('clients_index') }}" class="float-right">back to list</a>

    <a href="{{ path('clients_edit', {'id': client.id}) }}" class="btn btn-primary float-left">edit</a>

    {{ include('clients/_delete_form.html.twig') }}
{% endblock %}

src/templates/home/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>Examen Fernando Gil</h1>
    <a href="clients/">Ir a Catálogo</a>
{% endblock %}